image: node:20-alpine

stages:
  - test

ejecutar_pruebas:
  stage: test
  script:
    - echo "Instalando dependencias del proyecto..."
    - npm install
    - echo "Ejecutando las pruebas de Jest..."
    - npm test