image: node:20-alpine

# Agregamos el Caché
cache:
  paths:
    - node_modules/

# Definimos el nuevo orden de las etapas (Agregamos deploy)
stages:
  - validate
  - test
  - build
  - deploy

# Trabajo de seguridad
# Trabajo de seguridad
auditar_seguridad:
  stage: validate
  script:
    - npm install
    - echo "Auditando solo paquetes de producción..."
    - npm audit --omit=dev

# Tu trabajo original de pruebas
ejecutar_pruebas:
  stage: test
  script:
    - npm install
    - npm test

# El trabajo de empaquetado 
empaquetar_app:
  stage: build
  script:
    - echo "Aquí irían los comandos de Docker build..."

# --- NUEVO: Trabajo de Despliegue Continuo (CD) ---
desplegar_a_produccion:
  stage: deploy
  script:
    - echo "Iniciando Despliegue Continuo (CD)..."
    - echo "Conectando de forma segura al servidor Ubuntu..."
    - echo "Descargando la nueva versión y reiniciando el contenedor de Docker..."
    - echo "¡Tu API está en vivo!"
  only:
    - main # Esto asegura que el despliegue SOLO ocurra en la rama principal 